
# Define a custom bridge network for internal communication
networks:
  app_network:
    name: deploy_test_network
    driver: bridge

services:

  # --------------------------------------------------------
  # SERVICE: web (Vite Frontend / Nginx)
  # --------------------------------------------------------
  web:
    container_name: web
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: production
    env_file:
      - .env
    # FIX: Change the host port mapping to avoid port 80 conflict.
    # We map host port 8088 -> container port 80 (Nginx default).
    ports:
      - "8088:80"
    networks:
      - app_network
    restart: always
    # Domain reference for easier reverse proxy setup
    labels:
      - "traefik.http.routers.web.rule=Host(`fit.wsys.au`)"


  # --------------------------------------------------------
  # SERVICE: server (Hono Backend)
  # --------------------------------------------------------
  server:
    container_name: server
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      target: production
    env_file:
      - .env
    # The server runs on port 3000 inside the container
    # Mapping to host port 3000 (which is less likely to conflict)
    ports:
      - "3000:3000"
    networks:
      - app_network
    restart: always
    # Domain reference for easier reverse proxy setup
    labels:
      - "traefik.http.routers.server.rule=Host(`fit.api.wsys.au`)"
