packages:
  - apps/*
  - packages/*

catalog:
  '@orpc/client': ^1.10.0
  '@orpc/openapi': ^1.10.0
  '@orpc/server': ^1.10.0
  '@orpc/zod': ^1.10.0
  better-auth: ^1.3.28
  dotenv: ^17.2.2
  drizzle-orm: ^0.44.2
  hono: ^4.8.2
  tsdown: ^0.15.5
  typescript: ^5.8.2
  zod: ^4.1.11

onlyBuiltDependencies:
  - esbuild
